INSERT INTO CONFIGURATION (PROPIEDAD, VALOR) VALUES ('1', 'Valor 1');
INSERT INTO NICOLAS_ACHURI (ID,PREGUNTA,RESPUESTA) VALUES (10,'0','A');

----------------------------------------------------------------------
INSERT INTO NICOLAS_ACHURI (ID,PREGUNTA,RESPUESTA) VALUES (10,'1','B');
INSERT INTO NICOLAS_ACHURI (ID,PREGUNTA,RESPUESTA) VALUES (10,'2','C');
INSERT INTO NICOLAS_ACHURI (ID,PREGUNTA,RESPUESTA) VALUES (10,'3','D');
INSERT INTO NICOLAS_ACHURI (ID,PREGUNTA,RESPUESTA) VALUES (10,'4','B');
INSERT INTO NICOLAS_ACHURI (ID,PREGUNTA,RESPUESTA) VALUES (10,'5','C');
INSERT INTO NICOLAS_ACHURI (ID,PREGUNTA,RESPUESTA) VALUES (10,'6','C');
INSERT INTO NICOLAS_ACHURI (ID,PREGUNTA,RESPUESTA) VALUES (10,'7','A');
INSERT INTO NICOLAS_ACHURI (ID,PREGUNTA,RESPUESTA) VALUES (10,'8','D');
INSERT INTO NICOLAS_ACHURI (ID,PREGUNTA,RESPUESTA) VALUES (10,'9','A');
INSERT INTO NICOLAS_ACHURI (ID,PREGUNTA,RESPUESTA) VALUES (10,'10','B');
INSERT INTO NICOLAS_ACHURI (ID,PREGUNTA,RESPUESTA) VALUES (10,'11','C');
INSERT INTO NICOLAS_ACHURI (ID,PREGUNTA,RESPUESTA) VALUES (10,'12','D');
INSERT INTO NICOLAS_ACHURI (ID,PREGUNTA,RESPUESTA) VALUES (10,'13','B');
INSERT INTO NICOLAS_ACHURI (ID,PREGUNTA,RESPUESTA) VALUES (10,'14','A');
INSERT INTO NICOLAS_ACHURI (ID,PREGUNTA,RESPUESTA) VALUES (10,'15','C');