INSERT INTO CONFIGURATION (PROPIEDAD, VALOR) VALUES ('1', 'Valor 1');

INSERT INTO TOMAS_SUAREZ (PREGUNTA, LETRA_RESP, JUSTIFICACION) VALUES ('prueba1','a','ESTO ES UNA PRUEBA');
INSERT INTO TOMAS_SUAREZ (PREGUNTA, LETRA_RESP, JUSTIFICACION) VALUES ('prueba2','a','tomassss');
INSERT INTO TOMAS_SUAREZ (PREGUNTA, LETRA_RESP, JUSTIFICACION) VALUES ('1','b','');
INSERT INTO TOMAS_SUAREZ (PREGUNTA, LETRA_RESP, JUSTIFICACION) VALUES ('2','c','');
INSERT INTO TOMAS_SUAREZ (PREGUNTA, LETRA_RESP, JUSTIFICACION) VALUES ('3','d','');
INSERT INTO TOMAS_SUAREZ (PREGUNTA, LETRA_RESP, JUSTIFICACION) VALUES ('4','b','');
INSERT INTO TOMAS_SUAREZ (PREGUNTA, LETRA_RESP, JUSTIFICACION) VALUES ('5','c','');
INSERT INTO TOMAS_SUAREZ (PREGUNTA, LETRA_RESP, JUSTIFICACION) VALUES ('6','c','');
INSERT INTO TOMAS_SUAREZ (PREGUNTA, LETRA_RESP, JUSTIFICACION) VALUES ('7','a','');
INSERT INTO TOMAS_SUAREZ (PREGUNTA, LETRA_RESP, JUSTIFICACION) VALUES ('8','d','');
INSERT INTO TOMAS_SUAREZ (PREGUNTA, LETRA_RESP, JUSTIFICACION) VALUES ('9','b','');
INSERT INTO TOMAS_SUAREZ (PREGUNTA, LETRA_RESP, JUSTIFICACION) VALUES ('10','b','');
INSERT INTO TOMAS_SUAREZ (PREGUNTA, LETRA_RESP, JUSTIFICACION) VALUES ('11','d','');
INSERT INTO TOMAS_SUAREZ (PREGUNTA, LETRA_RESP, JUSTIFICACION) VALUES ('12','d','');
INSERT INTO TOMAS_SUAREZ (PREGUNTA, LETRA_RESP, JUSTIFICACION) VALUES ('13','b','');
INSERT INTO TOMAS_SUAREZ (PREGUNTA, LETRA_RESP, JUSTIFICACION) VALUES ('14','b','');
INSERT INTO TOMAS_SUAREZ (PREGUNTA, LETRA_RESP, JUSTIFICACION) VALUES ('15','c','');
