INSERT INTO CONFIGURATION (PROPIEDAD, VALOR) VALUES ('1', 'Valor 1');
INSERT INTO NICOLAS_ACHURI (ID,PREGUNTA,RESPUESTA) VALUES (0,'0','A');

INSERT INTO NICOLAS_ACHURI (ID,PREGUNTA,RESPUESTA) VALUES (1,'1','B');
INSERT INTO NICOLAS_ACHURI (ID,PREGUNTA,RESPUESTA) VALUES (2,'2','C');
INSERT INTO NICOLAS_ACHURI (ID,PREGUNTA,RESPUESTA) VALUES (3,'3','D');
INSERT INTO NICOLAS_ACHURI (ID,PREGUNTA,RESPUESTA) VALUES (4,'4','B');
INSERT INTO NICOLAS_ACHURI (ID,PREGUNTA,RESPUESTA) VALUES (5,'5','C');
INSERT INTO NICOLAS_ACHURI (ID,PREGUNTA,RESPUESTA) VALUES (6,'6','C');
INSERT INTO NICOLAS_ACHURI (ID,PREGUNTA,RESPUESTA) VALUES (7,'7','A');
INSERT INTO NICOLAS_ACHURI (ID,PREGUNTA,RESPUESTA) VALUES (8,'8','D');
INSERT INTO NICOLAS_ACHURI (ID,PREGUNTA,RESPUESTA) VALUES (9,'9','A');
INSERT INTO NICOLAS_ACHURI (ID,PREGUNTA,RESPUESTA) VALUES (10,'10','B');
INSERT INTO NICOLAS_ACHURI (ID,PREGUNTA,RESPUESTA) VALUES (11,'11','C');
INSERT INTO NICOLAS_ACHURI (ID,PREGUNTA,RESPUESTA) VALUES (12,'12','D');
INSERT INTO NICOLAS_ACHURI (ID,PREGUNTA,RESPUESTA) VALUES (13,'13','B');
INSERT INTO NICOLAS_ACHURI (ID,PREGUNTA,RESPUESTA) VALUES (14,'14','A');
INSERT INTO NICOLAS_ACHURI (ID,PREGUNTA,RESPUESTA) VALUES (15,'15','C');